global:
  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  localClusterDomain: local.example.com
  hubClusterDomain: hub.example.com

messaging:
  vibrationAlert: true
  vibrationAnomaly: true
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false

mqtt:
  broker:
    uri: "tcp://broker-amq-mqtt-all-0-svc:61616"
    clientId: "MQTT2KafkaRoute"
    topic:
      temperature: "iot-sensor/sw/temperature"
      vibration: "iot-sensor/sw/vibration"

kafka:
  broker:
    uri: "factory-kafka-cluster-kafka-bootstrap:9092"
    topic:
      temperature: "manuela-factory.iot-sensor-sw-temperature"
      vibration: "manuela-factory.iot-sensor-sw-vibration"

machine_sensor:
  bootstrap_image: quay.io/hybridcloudpatterns/iot-software-sensor:0.3.1
  bootstrap_tag: 0.3.1
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-machine-sensor/machine-sensor
  repo_name: iot-software-sensor
  tag: 0.3.1
  built_tags: []

iot_anomaly_detection:
  bootstrap_image: quay.io/hybridcloudpatterns/iot-anomaly-detection:0.3.2
  bootstrap_tag: 0.3.2
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-messaging/anomaly-detection
  repo_name: iot-anomaly-detection
  tag: 0.3.2
  built_tags: []

iot_consumer:
  bootstrap_image: quay.io/hybridcloudpatterns/iot-consumer:0.3.2
  bootstrap_tag: 0.3.2
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-messaging/messaging
  repo_name: iot-consumer
  tag: 0.3.2
  built_tags: []

iot_frontend:
  bootstrap_image: quay.io/hybridcloudpatterns/iot-frontend:0.3.1
  bootstrap_tag: 0.3.1
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-line-dashboard/line-dashboard
  repo_name: iot-frontend
  tag: 0.3.1
  built_tags: []
