apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: anomaly-detection
  name: anomaly-detection
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: false
  tags:
  - name: {{ .Values.iot_anomaly_detection.bootstrap_tag }}
    from:
      kind: DockerImage
      name: {{ .Values.iot_anomaly_detection.bootstrap_image }}
    importPolicy: {}
    referencePolicy:
      type: Local
{{- range .Values.iot_anomaly_detection.built_tags }}
  - name: {{ . | quote }}
    from:
      kind: DockerImage
      name: "{{ $.Values.global.imageregistry.hostname }}/{{ $.Values.global.imageregistry.account }}/{{ $.Values.iot_anomaly_detection.repo_name }}:{{ . }}"
    importPolicy: {}
    referencePolicy:
      type: Local
{{- end }}
