#!/bin/bash 

YOUR_USERNAME="CHANGEME"
YOUR_ROBOT_ACCOUNT_USERNAME="CHANGEME"
YOUR_ROBOT_ACCOUNT_PASSWORD="CHANGEME"
YOUR_GITHUB_USERNAME="CHANGEME"
YOUR_GITHUB_TOKEN="CHANGEME"
YOUR_AWS_ACCESS_KEY_ID="CHANGEME"
YOUR_AWS_SECRET_ACCESS_KEY="CHANGEME"
YOUR_GIT_ACCOUNT="CHANGEME"
YOUR_IMAGEREGISTRY_ACCOUNT="CHANGEME"
YOUR_IMAGEREGISTRY_HOSTNAME="CHANGEME"
YOUR_S3_BUCKET_REGION="us-east-2" # Default is us-east-2
YOUR_S3_BUCKET_NAME="industrial-edgep-$GUID"
YOUR_GIT_HOSTNAME="github.com" # Default is github.com
YOUR_VERSION="v2.3" # Default is v2.3

YOUR_CLUSTER_GROUP_NAME="datacenter"
YOUR_GLOBAL_PATTERN="industrial-edge"
YOUR_IMAGEREGISTRY_TYPE="quay"
YOUR_DEV_REVISION="main"




